### ISSUE TITLE
Add debian package to PPA

### ISSUE THREAD

**Issue by PanderMusubi** [GroundApps/ShoppingList_Desktop#3]
Please, add an Ubuntu debian package to PPA https://launchpad.net/~jklmnn/+archive/ubuntu/groundapps build for at least wily and xenial. Thanks

**Comment by jklmnn** [comment]
The package that is currently provided should also work on Debian, or did I misunderstand the question?

**Comment by PanderMusubi** [comment]
Ah, I am refering to the desktop application, not the server.

**Comment by jklmnn** [comment]
Oh, I see, my brain was in the wrong repo ;)
The desktop app is currently far from working, nothing except a layout prototype has been implemented.
I have currently no time to do this and unfortunately this seems to count for anyone else. Unless there's somebody who finds the time and motivation to continue this project, I doubt that there will ever be a working desktop app.
